name: vehicle_makes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^4.2.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  get_it: ^7.7.0
  injectable: ^2.4.1
  injectable_generator: ^2.6.1
  logger: ^2.3.0
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.9.0
  go_router: ^14.2.0
  flutter_launcher_icons: ^0.13.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  

flutter:
  uses-material-design: true
  assets:
    - .env
  
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Bold.ttf
      - asset: assets/fonts/Poppins-Italic.ttf
      - asset: assets/fonts/Poppins-BoldItalic.ttf
      - asset: assets/fonts/Poppins-Light.ttf
      - asset: assets/fonts/Poppins-LightItalic.ttf
      - asset: assets/fonts/Poppins-Medium.ttf
